# Generated by Django 4.1.5 on 2023-01-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppCoder", "0003_curso_entregable_estudiante"),
    ]

    operations = [
        migrations.CreateModel(
            name="Familiar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parentesco", models.CharField(max_length=40)),
                ("nombre", models.CharField(max_length=40)),
                ("edad", models.IntegerField()),
                ("fecha", models.DateField()),
            ],
        ),
    ]
